<li><!--Land: Deutschland-->
  <div class="collapsible-header"> <img src="http://www.nationalflaggen.de/images/flaggen/flagge-deutschland-flagge-rechteckig-50x83.gif" class="circle" style="width:15px; height:15px; vertical-align:middle"><b style="vertical-align:middle">   Deutschland</b></div>
  <div class="collapsible-body" style="background-color:#F5F5F5">
    <p>Amazingly, the Germans have only previously won this competition on one occasion. Six years ago they had a squad jammed full of talent as the likes of Mesut Ozil, Sami Khedira and Manuel Neuer stole the show. The current crop may not be quite as good, but it's still a strong unit, who are rightly regarded as the favourites to triumph. Providing that they can live up to the expectations, it will take a very good team to beat them.</p>
    <div class="divider"></div>
    <p style="background:#FBFBFB"> <b>Kurzinfo</b><br />
      Nachdem er Deutschland 2009 zur ersten und bisher einzigen UEFA-U21-Europameisterschaft führte, ist Horst Hrubesch mittlerweile wieder Trainer dieser Mannschaft und würde den großen Erfolg von damals gerne wiederholen. Sechs der Helden von Malmö vor fünf Jahren gehörten zu Deutschlands Kader bei der siegreichen FIFA-WM 2014 in Brasilien. Für Hrubesch geht es immer noch um dasselbe: "Meine Aufgabe ist es, die Spieler auf eine Art und Weise vorzubereiten, dass sie bereit sind, für Joachim Löw zu spielen", sagte er.</br>
      Das funktioniert, denn mit Marc-André ter Stegen, Kevin Volland, Max Meyer und Christian Günter sind schon einige Spieler aus seinem Kader für die A-Nationalmannschaft aufgelaufen. U21-Kapitän Volland stand sogar in Löws vorläufigem Kader für die Weltmeisterschaft und erzielte in der Qualifikation zur Endrunde in der Tschechischen Republik sechs Tore in ebenso vielen Spielen, darunter je eines in den Play-off-Spielen gegen die Ukraine (Gesamt: 5:0). Philipp und Jonas Hofmann, Moritz Leitner sowie Leonardo Bitencourt sind weitere wichtige Figuren in Hrubeschs Elf, während auch von Meyer (der als Spielmacher beim FC Schalke 04 spielt) und FC Barcelonas Schlussmann Ter Stegen einiges erwartet wird.</br>
      Die Qualifikation zur Endrunde verlief für Deutschland schon einmal reibungslos. Bereits einen Spieltag vor Schluss stand der Sieg in der Gruppe 6 fest, am Ende landete man acht Punkte vor Rumänien, das man am letzten Spieltag in Magdeburg mit 8:0 abfertigte. Dann bezwang man in den Play-offs ohne Gegentor die Ukraine. Insgesamt erzielte man 30:5 Tore, bester Torschütze war Philipp Hofmann mit sieben Treffern in zehn Spielen. In Israel 2013 schied Deutschland in der Gruppenphase aus, doch 2015 erwartet Hrubesch mehr: "Jeder, der mich kennt, weiß, dass ich nicht einfach nur an der Endrunde teilnehmen will. Diese Mannschaft ist in der Lage, den Titel zu gewinnen", sagte er.</p>
    <div class="divider"></div>
    <p style="background:#F5F5F5"> <b>Star: Kevin Volland</b><br />
      In what is a multi-talented Germany squad, captain Volland is the leader. He shook of the disappointment of not going to last year's World Cup in Brazil by scoring six goals in as many outings during the qualification phase for this tournament. The striker also weighed in with 10 goals last term for Hoffenheim, who have made it clear that they have no intention of selling one of their prized assets during the pre-season break. However, if he were to put in some eye catching performances in the Czech Republic - which he is certainly capable of doing - a transfer to a bigger club is not beyond the realms of possibility.</p>
    <div class="divider"></div>
    <p style="background:#FBFBFB"> <b>Links</b><br />
      <a href="http://de.uefa.com/under21/season=2015/teams/team=200047/squad/index.html">Mannschaft</a></p>
  </div>
</li><!--ENDE Deutschland-->

