<li><!--Land: Italien-->
  <div class="collapsible-header"> <img src="http://www.nationalflaggen.de/images/flaggen/flagge-italien-flagge-rechteckig-50x86.gif" class="circle" style="width:15px; height:15px; vertical-align:middle"><b style="vertical-align:middle">   Italien</b></div>
  <div class="collapsible-body" style="background-color:#F5F5F5">
    <p>No nation has won this title more times than the Azzurri, who have triumphed on five occasions. But, can they make it number six in the Czech Republic? Bookmakers regard them to be the fourth favourites, which is probably just about a fair summation. A lot will depend on Belotti, because defensively they are expected to be traditionally tight.</p>
    <div class="divider"></div>
    <p style="background:#FBFBFB"> <b>Kurzinfo</b><br />
      Der fünfmalige Titelträger Italien hat sich nach einem mehr als holperigen Start in der Qualifikation doch noch für die Endrunde in der Tschechischen Republik qualifiziert. Im ersten Spiel der Gruppe 9 setzte es eine 1:3-Heimniederlage gegen Belgien, doch mit einem 1:0-Sieg in Genk gaben die Italiener nur vier Wochen später die richtige Antwort. Doch es folgte mit dem 0:1 in Serbien ein weiterer unerwarteter Rückschlag. Beim Rückspiel in Pescara lag das Team von Trainer Luigi Di Biagio schon nach 13 Minuten mit 0:2 hinten, doch dank zweier Tore von Andrea Belotti reichte es am Ende zu einem 3:2-Erfolg und dem Gruppensieg.</br>
      In den beiden Play-offs gegen die Slowakei war dann erneut Belotti von US Città di Palermo mit zwei Treffern der Matchwinner, insgesamt setzten sich die Azzurrini mit 4:2 durch. Neben Belotti glänzten im Angriff auch seine beiden Kollegen Domenico Berardi und Federico Bernardeschi, das Trio erhielt inzwischen den Spitznamen 'Il Tridente 3B'. Stefano Sturaro und Lorenzo Crisetig ziehen im Mittelfeld die Fäden, beide gehören auch in der Serie A bei ihren Klubs Genoa CFC und Cagliari Calcio zu den Stammkräften. Torhüter Francesco Bardi und die Abwehrspieler Cristiano Biraghi (beide AC Chievo Verona) und Davide Zappacosta (Atalanta BC) weisen ebenfalls Erfahrung in der Serie A auf.</br>
      2013 erreichten die Azzurrini bei der Endrunde in Israel das Endspiel, wo man allerdings in Jerusalem beim 2:4 gegen Spanien chancenlos war. Di Biagio, einstmals im Trikot von AS Roma und dem FC Internazionale Milano, ersetzte anschließend Devis Mangia auf dem Trainerposten und ist mit den Fortschritten zufrieden. "Wir wussten angesichts der starken Konkurrenz von Anfang an, wie schwer es werden würde, uns zu qualifizieren", sagte er. "Wir müssen hart daran arbeiten, uns weiter zu verbessern, aber der Enthusiasmus in unserer Truppe ist sehr groß."</p>
    <div class="divider"></div>
    <p style="background:#F5F5F5"> <b>Star: Andrea Belotti</b><br />
     Starting now, it's going to be a big few months for Belotti. At this tournament, he is Italy's main striker and much will be expected of the 21-year-old. He found the net six times in qualifying, which was four more times than any of his teammates. Meanwhile, at club level with Palermo, he will be charged with the task of replacing Juventus-bound Paulo Dybala. That is by no means an easy feat, but he does possess the workrate levels and clinical touch to be a successful forward in Serie A.</p>
    <div class="divider"></div>
    <p style="background:#FBFBFB"> <b>Links</b><br />
      <a href="http://de.uefa.com/under21/season=2015/teams/team=200066/squad/index.html">Mannschaft</a></p>
  </div>
</li><!--ENDE Italien-->