<li><!--Land: Portugal-->
  <div class="collapsible-header"> <img src="http://www.nationalflaggen.de/images/flaggen/flagge-portugal-flagge-rechteckig-50x75.gif" class="circle" style="width:15px; height:15px; vertical-align:middle"><b style="vertical-align:middle">   Portugal</b></div>
  <div class="collapsible-body" style="background-color:#F5F5F5">
    <p>Qualifying in such style brings with it a level of expectation. The big question is, how will Jorge's men cope? They certainly have plenty of goals in the team, so much will be decided on how they defend against England and Italy, who are likely to be their main competitors for a place in the semi-finals. Having never previously won the competition, they may well have their strongest squad of recent times to end the wait.</p>
    <div class="divider"></div>
    <p style="background:#FBFBFB"> <b>Kurzinfo</b><br />
      Portugal ist die einzige Mannschaft, die in der Qualifikation keinen einzigen Punkt abgegeben hat, denn von zehn Spielen wurde zehn gewonnen. Damit wurde erstmals seit 2007 die Endrunde erreicht – damals belegten sie den dritten Platz. Dies nun ist die siebte Endrunde, die beste Leistung zeigten die Portugiesen 1994, als sie hinter Italien Platz zwei belegten; mit späteren Stars wie Luís Figo und Rui Costa in ihren Reihen.</br>
     Die Portugiesen begannen die Qualifikation mit einem eindrucksvollen 5:1-Heimsieg gegen Norwegen. Am Ende wurde die Gruppe 8 ohne Punktverlust gewonnen, 22 Tore wurde erzielt und nur sechs kassiert. Das 4:3 in Israel war ein Vorbote dessen, was in den Play-offs gegen die Niederlande passierte, als sie sich mit insgesamt 7:4 durchsetzten. Das Rückspiel in Pacos de Ferreira gewannen sie mit 5:4.</br>
      Ricardo, Stürmer des FC Porto, traf in dieser Partie zweimal, womit er am Ende fünf Treffer auf dem Konto hatte und damit bester Schütze seiner Mannschaft war. Neben Paulo Oliveira, Innenverteidiger von Sporting Clube de Portugal, war er einer von zwei Spielern, die in jeder Partie auf dem Platz standen. Im Mittelfeld agierte mit Bernardo Silva (er hat in dieser Saison in der UEFA Champions League gespielt, nachdem er von SL Benfica zum AS Monaco FC ausgeliehen wurde) ein weiterer wichtiger Offensivmann der Portugiesen, der vier Tore schoss und zwei vorbereitete, während William Carvalho und André Gomes derart beeindruckten, sodass sie seit dem Start der Qualifikation in der A-Nationalmannschaft zu bewundern sind.</br>
      Trainer Rui Jorge hat seit 2010 das Amt inne, und nachdem sie die Teilnahme an der Endrunde 2013 verpasst hatten, hat sich seine Mannschaft weiterentwickelt. "Was wir geschafft haben, ist wunderbar, aber auch total verdient für diese Spieler, die die Gelegenheit haben, auf einer sehr wichtigen Bühne zu spielen", sagte er. "Wir haben eine starke Mannschaft, aber ich würde uns nicht als Favoriten bezeichnen. Unser erstes Ziel ist es, die Gruppenphase zu überstehen und einen Platz bei den Olympischen Spielen in Brasilien zu buchen."</p>
    <div class="divider"></div>
    <p style="background:#F5F5F5"> <b>Star: William Carvalho</b><br />
     Having been linked with the likes of Manchester United, Liverpool and Arsenal in recent years, a lot of eyes will be on Carvalho this summer. He may have only played three qualification matches, largely due to his commitments with the senior side, but he still contributed two goals. With 12 full caps to his name, much will be expected of the 23-year-old, who will take up a holding role in the heart of the midfield. Impressive showings in the Czech Republic could, after so much speculation, finally earn him a move away from Sporting Lisbon.</p>
    <div class="divider"></div>
    <p style="background:#FBFBFB"> <b>Links</b><br />
      <a href="http://de.uefa.com/under21/season=2015/teams/team=200110/squad/index.html">Mannschaft</a></p>
  </div>
</li><!--ENDE Portugal-->